# Travis doesn't have a fortran build config, so we'll use c as a base and
# create our own environment
language: c
sudo: required

env:
    global:
        - FC=gfortran-4.8
        - OMPI_FC=${FC}
install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    # sudo apt-get install gcc-4.8 gfortran-4.8 libgomp1 openmpi-bin libopenmpi-dev liblapack-dev libblas-dev
    - sudo apt-get install gcc-4.8 gfortran-4.8 liblapack-dev libblas-dev
    - cd ..
    - git clone https://github.com/fireball-dft/fireball-master.git
    - cd fireball-fireball/src
    - make fireball.x
    - make lfireball.x
    

script: true
    # make check PFUNIT=pfunit

after_success: true
    # find .
    # codecov --gcov-exec=gcov-4.8
